name: ADC website deployment [STAGE]
run-name: Deploy ADC website to STAGE [@${{ github.actor }}]

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: STAGE
