name: ADC website deployment
run-name: Deploy ADC website [@${{ github.actor }}]

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add metadata file to deployment package
        run: |
          export TZ=US/Pacific
          METADATA_FILE_NAME=metadata.json
          METADATA_FILE_PATH=${{ github.workspace }}/web/src/$METADATA_FILE_NAME
          if [ "$GITHUB_REF_NAME" == "main" ]; then VERSION="v0.0.0.0-ephemeral-release"; else VERSION=$GITHUB_REF_NAME; fi
          NEW_CONTENT="{
            \"version\": \"$VERSION\",
            \"released-at\": \"$(date +%d-%m-%Y" "%H:%M:%S) PST\"
          }"
          echo "$NEW_CONTENT" > $METADATA_FILE_PATH

      - name: Install dependencies
        run: |
          npm install
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::030460844096:role/ADC_DeployWebApp
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-west-1

      - name: Create stack
        run: |
          cdk deploy --require-approval never \
            -c aliasRecordName=${{ vars.ALIAS_RECORD_NAME }} \
            -c bucketName=${{ vars.BUCKET_NAME }} \
            -c cachePolicyName=${{ vars.CACHE_POLICY_NAME }} \
            -c deploymentName=${{ vars.DEPLOYMENT_NAME }} \
            -c distributionName=${{ vars.DISTRIBUTION_NAME }} \
            -c domains=${{ vars.DOMAINS }} \
            -c viewerRequestHandlerName=${{ vars.VIEWER_REQUEST_HANDLER_NAME }} \
            -c host=${{ vars.HOST }} \
            -c stackName=${{ vars.STACK_NAME }} \
            -c hostedZoneId=${{ vars.HOSTED_ZONE_ID }} \
            -c zoneName=${{ vars.ZONE_NAME }} \

  smoke-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    needs: deploy-infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Smoke test a production environment
        if: ${{ ! vars.HOST }}
        run: bash web/test/scripts/smoke-test-prod.sh ${{ vars.PRIMARY_DOMAIN }}

      - name: Smoke test a pre-production environment
        if: ${{ vars.HOST }}
        run: bash web/test/scripts/smoke-test-preprod.sh ${{ vars.PRIMARY_DOMAIN }}
