name: ADC website deployment [PRODUCTION]
run-name: Deploy ADC website to PRODUCTION [@${{ github.actor }}]

on:
  workflow_dispatch:

jobs:
  deploy-production:
    name: deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: PROD
