name: ADC website deployment [DEV]
run-name: Deploy ADC website to DEV [@${{ github.actor }}]

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-production:
    name: deploy
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: DEV
